apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: centos-example2
  annotations:
    athena-regex: (.*)
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  labels:
    lab: example    
spec:
  rules:
  - host: test.athenaprojectlab.com
    http:
      paths:
      - path: /example/centos/tty/
        backend:
          serviceName: centos-tty
          servicePort: 80

